library(shiny)
library(DT)
library(RColorBrewer)
library(reticulate)
library(tiff)
library(png)

# Define any Python packages needed for the app here:
# (Make sure these are installed in your Python environment)
# Begin app server
shinyServer(function(input, output) {
  
  # ------------------ App virtualenv setup (Do not edit) ------------------- #
  virtualenv_create("py3-virtualenv", python = "/usr/bin/python3")
  use_virtualenv("py3-virtualenv", required = TRUE)
  observeEvent(input$download, { packages <- input$dependencies
  PYTHON_DEPENDENCIES <- strsplit(packages, ",")
  for (pkg in PYTHON_DEPENDENCIES) {
    py_install(pkg, envname = "py3-virtualenv")
  }
  
  })
  
  # ------------------ App server logic (Edit anything below) --------------- #
  # Import python functions to R
  
  
  # Image upload and conversion from TIFF to PNG
  observeEvent(input$done, { file <- input$files
  reticulate::source_python(file)
  })
  
  # Placeholder for cells function or any other operation to handle file path input
  output$contents <- renderTable({
    # Trigger this reactive block when the user inputs a file path and clicks a button
    req(input$dp, input$rp, input$analyze_btn) # Require that input$fp is not NULL
    # Call the Python function
    results_path <- py$main(input$dp, input$rp)
    
    # Read the CSV file generated by Python{
    read.csv(input$rp)
  })
  output$tbl <- renderDT({
    req(input$show_btn)
    read.csv(input$rp)
  })
  
  # Display info about the system running the code
  output$sysinfo <- DT::renderDataTable({
    s = Sys.info()
    df = data.frame(Info_Field = names(s),
                    Current_System_Setting = as.character(s))
    return(datatable(df, rownames = F, selection = 'none',
                     style = 'bootstrap', filter = 'none', options = list(dom = 't')))
  })
  
  # Display system path to python
  output$which_python <- renderText({
    paste0('which python: ', Sys.which('python'))
  })
  
  # Display Python version
  output$python_version <- renderText({
    rr = reticulate::py_discover_config(use_environment = 'python35_env')
    paste0('Python version: ', rr$version)
  })
  
  # Display RETICULATE_PYTHON
  output$ret_env_var <- renderText({
    paste0('RETICULATE_PYTHON: ', Sys.getenv('RETICULATE_PYTHON'))
  })
  
  # Display virtualenv root
  output$venv_root <- renderText({
    paste0('virtualenv root: ', reticulate::virtualenv_root())
  })
  
})